### PR TITLE
Add containerized build system (optional)

### PR DESCRIPTION
**Pull request by macegr**
(Optional) This provides a way to use Docker if wanted, but does not prevent installing and running the toolchain natively if desired.

If you use Docker on your development computer, this implements the following:
- Fetch a minimal Debian Linux image
- Install the packages needed to run the toolchain on the image
- Fetch and extract the ECP5 toolchain into the image
- Simple scripts to create the image, load a container and run `make` or other commands in it

Once the image is built, the instructions for use are nearly identical to natively-installed tools. Go to an app directory and run `../badge_container make` and it'll start up a container, do all the build tasks, and dump the resulting output in the same folder. All without chasing down dependencies, installing more tools, and modifying environment variables on your computer. Note: I don't have access to hardware, so can't confirm the flash functions work at the moment. Will be able to test in a few days!

Why do this? It'll work on any setup that can run Docker, isolated into a fresh image with just the stuff the toolchain needs, so that there are no conflicts with your own setup (in both directions). Yet you can still edit your source files natively, no transferring back and forth from a VM or having to work entirely inside a VM. On macOS Catalina, the toolchain binaries inside a container won't require individual approval before running.

### CODE REVIEW

**Comment by abhishek-kakkar** [comment]
Hi @macegr, thanks for this one! I had been trying to set up a CI environment using Drone CI for building badge images and already made something similar @ https://github.com/theembeddedkitchen-bot/ecp5-toolchain-docker . Feel free to drop in a PR there as well. It is also on Docker hub so people can actually download it and use it.

**Comment by Spritetm** [comment]
Cool, thanks! Can you move the readme file to e.g. doc/toolchain_docker.md, for consistency? Feel free to add a link in the main README.md file as well.

**Comment by macegr** [comment]
@Spritetm Thanks, I made the suggested changes!

**Comment by macegr** [comment]
@abhishek-kakkar It looks quite similar, I think this means it's a good idea :) I will certainly be using a container for this, having struggled with lasting configuration problems many times over the years. I'm attempting to keep things small by starting from bitnami's minideb image rather than ubuntu:latest, though the toolchain extracts out to fill most of the 1.9GB the final image requires.

The image itself is not the real contribution here, rather the builder and runner scripts which handle some of the options some newer Docker users might miss...and then wonder why their images are so huge, and why 40 old containers have just used up all their disk space.

**Comment by Spritetm** [comment]
Cool, thanks!

**Pull request merged**
