### PR TITLE
Circuit Invaders Game

### PR DESCRIPTION
**Pull request by ANDnXOR**
Another simple game to demonstrate the badge graphics engine. Avoid resistors, capacitors, and 18650s. Shoot "photons" from your LED to destroy the "aliens".

### CODE REVIEW

**Comment by Spritetm** [comment]
Thanks! There's a fair amount of build artifacts (build directory, .sym file, ....) in the tree at the moment. Can you remove that and add a .gitignore for them?

**Comment by ANDnXOR** [comment]
Oh derp. Will do

**Comment by smunaut** [comment]
Is there any benefit to keeping all the history vs just doing a rebase and squash ?

**Comment by Spritetm** [comment]
That is a discussion that be held and then fall to either sides on a more serious project. I'm a simple guy here: I see a result that I like and that's mergable, I press 'merge pull request'.

**Comment by ANDnXOR** [comment]
Either way, doesn't matter to me. History is on my github anyways if people are really concerned about this amazing piece of work.

**Comment by Spritetm** [comment]
Just gave it a test, you may want to work on gameplay a bit more if you want this to be more than an example... I can finish every level up to level 16 by keeping A pressed; I die at level 16 because that is a killscreen as my bullets don't seem to move or come out anymore.
(Note that if you don't want to do that, that's fine too, if any it serves as an example.)

**Comment by daveshah1** [comment]
> That is a discussion that be held and then fall to either sides on a more serious project. I'm a simple guy here: I see a result that I like and that's mergable, I press 'merge pull request'.

They weren't so big here so it doesn't really matter; but where build results have been accidentally added and are then deleted in a subsequent commit they bloat the repository forever - whereas they wouldn't with a squash/rebase.

**Comment by ANDnXOR** [comment]
I'll work on the gameplay, wanted to get at least an example in since HaD is in a week and I have some personal commitments taking time away the next few days.

**Pull request merged**
