### PR TITLE
Build fixes / Improvements, including Windows build

### PR DESCRIPTION
**Pull request by smunaut**
This now build on windows under msys/cygwin shell or a WSL shell.

Still doesn't work under cmd.exe or powershell because "mkdir -p .deps" fails there, and not sure
how to handle that ...

### CODE REVIEW

**Comment by Spritetm** [comment]
LGTM, but do we actually need/use chmod anywhere? Perhaps better to get rid of the lines setting that up, to prevent confusion.

**Comment by smunaut** [comment]
It's used just to remove the executable bit on rom.bin .... Completely not necessary IMHO but I didn't want to remove it, but yeah, that would make things simpler.

**Comment by Spritetm** [comment]
Check. If you can add a commit that removes those lines, I'll merge.

**Comment by smunaut** [comment]
Updated to remove CHMOD.
Also added a commit that creates an index into the gloss.a archive. That was needed by Sophi when building on OSX for some reason ...

**Comment by Spritetm** [comment]
Awesomesauce, thanks!

**Pull request merged**
