### PR TITLE
soc: Remove custom bram_replace tool in favor of the ecpbram utility

### PR DESCRIPTION
**Pull request by smunaut**
Now that the toolchain has a standard tool to accomplish the same task
I think it's best to use it given the goal of the badge is to promote
the opentools and serve as an "example" of how to do things.

Signed-off-by: Sylvain Munaut <tnt@246tNt.com>

### CODE REVIEW

**Comment by Spritetm** [comment]
I have no issues nixing my tool, but I'd like to make sure I don't strand people first... so not merging right now.

@xobs Is the bram tool also in the pre-built toolchains already?

**Comment by xobs** [comment]
Oh.  That would be why it wasn't built.  It's only 15 days old.

I don't have it packaged up in the ecp5 toolchain yet, but it already has Windows compatibility for when I do package everything up (https://github.com/SymbiFlow/prjtrellis/commit/089efdc763601da40533b902f51d34686e9361d7#diff-d878dbb0f1dc9f471eb1e03b88d721fd).  I'll cut another release of the toolchain on Monday.

**Comment by smunaut** [comment]
The new toolchain now includes ecpbram and it works fine under linux / windows / osx.

**Comment by Spritetm** [comment]
kk

**Pull request merged**
